### ISSUE TITLE
variant filtering for tucon task generates a file name too long for the OS to handle

### ISSUE THREAD

**Issue by denriquez** [tgen/tempe#10]
**tempe version:** 1.1.0
**task:** variant filtering (tucon)
**Issue:** An unhandled exception occurred when a script was being generated. This reason for this error is because the name of the file was too long. Jetstream continues to run but the connection with Slurm seems broken. 
**Example of error message (paths and sample names were modified):**
 ```
[2023-01-04 19:38:53]: Unhandled exception in a task future: <Task finished coro=<SlurmSingularityBackend.spawn() done, defined at $HOME/.local/lib/python3.7/site-packages/jetstream/backends/slurm_singularity.py:188> exception=OSError(36, 'File name too long')>
Traceback (most recent call last):
  File "$HOME/.local/lib/python3.7/site-packages/jetstream/runner.py", line 277, in handler
    res = future.result()
  File "$HOME/.local/lib/python3.7/site-packages/jetstream/backends/slurm_singularity.py", line 287, in spawn
    input_file_validation=self.input_file_validation
  File "$HOME/.local/lib/python3.7/site-packages/jetstream/backends/slurm_singularity.py", line 686, in sbatch
    with open( sbatch_script_filename, "w" ) as sbatch_script_file:
OSError: [Errno 36] File name too long: '$USER_SCRATCH/tempe/EXAMPLE_01/jetstream/cmd/1111111111111_variant_filtering_EXAMPLE_01_L0001_GermlineDNA-EXAMPLE_01_L0002_TumorDNA_tucon_EXAMPLE_01_L0001_GermlineDNA-EXAMPLE_01_L0002_TumorDNA_vep_parabricks.sbatch'
[2023-01-04 19:38:53]: Slurm job monitor stopped!
[2023-01-04 19:38:53]: Exception during singularity prepull:
```

**Comment by denriquez** [comment]
Same issue found with the task, variant filtering for sigprofiler.

**Comment by bryce-turner** [comment]
Changes made in dc2312f

I think a larger scale change might be a better change in the future - for example someone could submit a config with super long sample names, this would break every file creation. An idea is to instead use the task identity for the file path since that should be a unique hash (less than 255 characters?), if not we could use a checksum of the task name.

**Comment by bryce-turner** [comment]
Resolved by https://github.com/tgen/jetstream/pull/152
